### ISSUE TITLE
review sentence

### ISSUE THREAD

**Issue by thegostep** [pokt-foundation/pocket-dao-voting-token#1]
https://github.com/pokt-foundation/pocket-dao-voting-token/blob/dc5424bdb3e5dfd80f98e5727e268c4742d55303/contracts/POKTDAO.sol#L13

**Comment by antron3000** [comment]
No problem, just a placeholder sentence for now

**Comment by JackALaing** [comment]
Let's change it to "The POKT DAO Vote Token is a non transferable token that holders use to vote by signing messages."

**Comment by antron3000** [comment]
done
